# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from math import sqrt
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyCalculator(object):
    def setupUi(self, MyCalculator):
        MyCalculator.setObjectName("MyCalculator")
        MyCalculator.resize(480, 550)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MyCalculator)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_16 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 2, 0, 1, 4)
        self.pushButton_14 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 3, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 3, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 4, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 4, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(MyCalculator)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 4)
        self.pushButton_17 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 3, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 5, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 6, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 7, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 7, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 4, 3, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 5, 3, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 6, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 7, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 7, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(MyCalculator)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 5, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 4, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 6, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(MyCalculator)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 5, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        def fun7() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "7")
           
        self.pushButton.clicked.connect(fun7)
        def fun1() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "1")
        self.pushButton_10.clicked.connect(fun1)   
        def fun2() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "2")
        self.pushButton_11.clicked.connect(fun2)
        def fun3() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "3")
        self.pushButton_12.clicked.connect(fun3)
        def fun4() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "4")
        self.pushButton_3.clicked.connect(fun4)
        def fun5() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "5")
        self.pushButton_4.clicked.connect(fun5)
        def fun6() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "6")
        self.pushButton_7.clicked.connect(fun6)
        def fun8() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "8")
        self.pushButton_5.clicked.connect(fun8)
        def fun9() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "9")
        self.pushButton_8.clicked.connect(fun9)
        def fun0() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "0")
        self.pushButton_6.clicked.connect(fun0)
        def plus() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "+")
        self.pushButton_20.clicked.connect(plus)
        def division() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "/")
        self.pushButton_15.clicked.connect(division)
        def sub() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "-")
        self.pushButton_19.clicked.connect(sub)
        def multipy() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "*")
        self.pushButton_18.clicked.connect(multipy)
        def squre() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + "**2")
        self.pushButton_13.clicked.connect(squre)
        def clear() :
            self.lineEdit.clear()
            
        self.pushButton_16.clicked.connect(clear)
        def sqrtt() :
            text = self.lineEdit.text()
            t = float(text)
            s = sqrt(t)
            self.lineEdit.setText(str(s))
        self.pushButton_14.clicked.connect(sqrtt)
        def equasion() :
            text = self.lineEdit.text()
            result = eval(text)
            self.lineEdit.setText(str(result))
        self.pushButton_21.clicked.connect(equasion)
        def dot() :
            text = self.lineEdit.text()
            self.lineEdit.setText(text + ".")
        self.pushButton_9.clicked.connect(dot)

        def backshift() :
            text = self.lineEdit.text()
            m = text.replace(text[-1] , "")
            self.lineEdit.setText(m)
        self.pushButton_17.clicked.connect(backshift)
        
        self.retranslateUi(MyCalculator)
        QtCore.QMetaObject.connectSlotsByName(MyCalculator)
        MyCalculator.setTabOrder(self.pushButton_10, self.pushButton_11)
        MyCalculator.setTabOrder(self.pushButton_11, self.pushButton_12)
        MyCalculator.setTabOrder(self.pushButton_12, self.pushButton_3)
        MyCalculator.setTabOrder(self.pushButton_3, self.pushButton_4)
        MyCalculator.setTabOrder(self.pushButton_4, self.pushButton_7)
        MyCalculator.setTabOrder(self.pushButton_7, self.pushButton)
        MyCalculator.setTabOrder(self.pushButton, self.pushButton_5)
        MyCalculator.setTabOrder(self.pushButton_5, self.pushButton_8)
        MyCalculator.setTabOrder(self.pushButton_8, self.pushButton_2)
        MyCalculator.setTabOrder(self.pushButton_2, self.pushButton_6)
        MyCalculator.setTabOrder(self.pushButton_6, self.pushButton_9)
        MyCalculator.setTabOrder(self.pushButton_9, self.pushButton_21)
        MyCalculator.setTabOrder(self.pushButton_21, self.pushButton_20)
        MyCalculator.setTabOrder(self.pushButton_20, self.pushButton_19)
        MyCalculator.setTabOrder(self.pushButton_19, self.pushButton_18)
        MyCalculator.setTabOrder(self.pushButton_18, self.pushButton_17)
        MyCalculator.setTabOrder(self.pushButton_17, self.pushButton_15)
        MyCalculator.setTabOrder(self.pushButton_15, self.pushButton_14)
        MyCalculator.setTabOrder(self.pushButton_14, self.pushButton_13)
        MyCalculator.setTabOrder(self.pushButton_13, self.pushButton_16)
        MyCalculator.setTabOrder(self.pushButton_16, self.lineEdit)

    def retranslateUi(self, MyCalculator):
        _translate = QtCore.QCoreApplication.translate
        MyCalculator.setWindowTitle(_translate("MyCalculator", "My Calculator"))
        self.pushButton_16.setText(_translate("MyCalculator", "C"))
        self.pushButton_14.setText(_translate("MyCalculator", "√x"))
        self.pushButton_15.setText(_translate("MyCalculator", "➗"))
        self.pushButton_10.setText(_translate("MyCalculator", "1"))
        self.pushButton_13.setText(_translate("MyCalculator", "x^2"))
        self.pushButton_11.setText(_translate("MyCalculator", "2"))
        self.pushButton_17.setText(_translate("MyCalculator", "<---"))
        self.pushButton_4.setText(_translate("MyCalculator", "5"))
        self.pushButton_8.setText(_translate("MyCalculator", "9"))
        self.pushButton_6.setText(_translate("MyCalculator", "0"))
        self.pushButton_9.setText(_translate("MyCalculator", "."))
        self.pushButton_18.setText(_translate("MyCalculator", "X"))
        self.pushButton_19.setText(_translate("MyCalculator", "__"))
        self.pushButton_20.setText(_translate("MyCalculator", "+"))
        self.pushButton_2.setText(_translate("MyCalculator", "off"))
        self.pushButton_21.setText(_translate("MyCalculator", "=="))
        self.pushButton.setText(_translate("MyCalculator", "7"))
        self.pushButton_3.setText(_translate("MyCalculator", "4"))
        self.pushButton_12.setText(_translate("MyCalculator", "3"))
        self.pushButton_5.setText(_translate("MyCalculator", "8"))
        self.pushButton_7.setText(_translate("MyCalculator", "6"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyCalculator = QtWidgets.QWidget()
    ui = Ui_MyCalculator()
    ui.setupUi(MyCalculator)
    MyCalculator.show()
    sys.exit(app.exec_())
